version: '3.9'

services:
  # üßë‚Äçüíº User Service
  user-db:
    image: postgres:15
    container_name: ecomicro-user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    ports:
      - "5435:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: ecomicro-user-service
    environment:
      DB_HOST: user-db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: userdb
      PORT: 8083
    depends_on:
      - user-db
    ports:
      - "8083:8083"

  # üì¶ Product Service
  product-db:
    image: postgres:15
    container_name: ecomicro-product-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: productdb
    ports:
      - "5436:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: ecomicro-product-service
    environment:
      DB_HOST: product-db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: productdb
      PORT: 8081
    depends_on:
      - product-db
    ports:
      - "8081:8081"

  # üè¨ Inventory Service
  inventory-db:
    image: postgres:15
    container_name: ecomicro-inventory-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: inventorydb
    ports:
      - "5437:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: ecomicro-inventory-service
    environment:
      DB_HOST: inventory-db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: inventorydb
      PORT: 8082
    depends_on:
      - inventory-db
    ports:
      - "8082:8082"

  # üßæ Order Service
  order-db:
    image: postgres:15
    container_name: ecomicro-order-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: orderdb
    ports:
      - "5438:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: ecomicro-order-service
    environment:
      DB_HOST: order-db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: orderdb
      USER_SERVICE_URL: http://user-service:8083
      PRODUCT_SERVICE_URL: http://product-service:8081
      INVENTORY_SERVICE_URL: http://inventory-service:8082
      PORT: 8084
    depends_on:
      - order-db
      - user-service
      - product-service
      - inventory-service
    ports:
      - "8084:8084"

  
      

volumes:
  user-db-data:
  product-db-data:
  inventory-db-data:
  order-db-data:
